---
title: "Box 4.1"
author: "Andrew MacDonald, after Vellend 201X"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Box4_1}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

## Simulating neutral dynamics in a local, two species community

```{r}
## set seed, making our example reproducible
set.seed(2)

## specify initial community and time instructions
J <- 50
init.1 <- J / 2
COM <- vector(length = J)

COM[1:init.1] <- 1
COM[(init.1 + 1):J] <- 2

num.years <- 50
year <- 2

## Set up vector for data collection
freq.1.vec <- vector(length = num.years)
freq.1.vec[1] <- init.1 / J

## run simulation
for(i in 1:(J * (num.years - 1))) {
  
  freq.1 <- sum(COM == 1)
  Pr.1  <- freq.1 / J
  COM[ceiling(J * runif(1))] <- sample(c(1, 2), 1, 
                                       prob = c(Pr.1, 1 - Pr.1))
  
  if (i %% J == 0){
    freq.1.vec[year] <- sum(COM == 1) / J
    year <- year + 1
  }
}

plot(1:num.years, freq.1.vec, type = "l", 
     xlab = "Time", 
     ylab = "Frequency of species 1", 
     ylim = c(0, 1))
```

### Detailed description of the code:

1. Define the local commmunity size, `J` . `J` is defined as an object, and ` <- ` places the number 50 in this object:

```{r}
## specify initial community and time instructions
J <- 50
init.1 <- J / 2
COM <- vector(length = J)
```

2. Define the initial population size of species 1, `init.1` . By default, the initial population size of species 2 will be `J – init.1`:

```{r}
COM[1:init.1] <- 1
COM[(init.1 + 1):J] <- 2
```

